# Generated by Django 2.0 on 2019-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190420_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_to',
            field=models.URLField(max_length=300),
        ),
    ]
